afes-website/back

- app/Http/Controllers/AdminAuthController.php
> Fix #3:複数ログインに対応

- app/Exceptions/Handler.php
> #06 ValidationException Handlerを追加

- app/Http/Controllers/AdminAuthController.php
- app/Models/AdminUser.php
- routes/web.php
- tests/AdminAuthJwtTest.php
> #8 change password

- app/Http/Controllers/AdminAuthController.php
- app/Http/Controllers/BlogArticleController.php
- app/Http/Controllers/BlogController.php
- app/Http/Controllers/BlogRevisionController.php
- app/Http/Controllers/WriterAuthController.php
- app/Http/Resources/ArticleResource.php
- app/Http/Resources/RevisionResource.php
- app/Models/Article.php
- app/Models/Revision.php
- app/Models/WriterUser.php
- app/Providers/AdminAuthServiceProvider.php
- app/Providers/WriterAuthServiceProvider.php
- bootstrap/app.php
- config/auth.php
- database/factories/ModelFactory.php
- database/migrations/2020_02_16_035148_create_revisions_table.php
- database/migrations/2020_02_16_072026_create_articles_table.php
- database/migrations/2020_02_17_130955_create_writer_users_table.php
- routes/web.php
- tests/AdminAuthJwtTest.php
- tests/BlogArticleTest.php
- tests/BlogRevisionTest.php
- tests/WriterAuthJwtTest.php
issue: #5 
issue: afes-website/docs#7
検討すべき事
- timestampの形式をどうするか
> #5 ブログのバックエンドの作成

- .github/workflows/deploy_product.yml
- .github/workflows/deploy_test.yml
> デプロイのエラー修正

- app/Http/Controllers/BlogArticleController.php
#25 
クオートで区切りが発生しないようにするのは面倒なのでなし。なくてもそんなに困らないでしょ
> #25: ブログ検索

- database/migrations/2020_03_11_021218_expand_images_blob.php
ALTERを生で書いた。MySQLとSQLite以外が非対応となってしまったが、まあいいでしょう
> [hotfix] #31: 画像contentの型がLONGBLOBじゃなかった

- app/Http/Controllers/BlogRevisionController.php
- tests/BlogRevisionTest.php
ここで防げば他はいらないと考えています (脆弱性とか見えたらおしえてください)
> #44: ブログ記事path制限

- app/Http/Controllers/BlogArticleController.php
- tests/BlogArticleTest.php
~ごにょごにょやることで実装できます。計算量はO(N)です。~
> #40: articleのauthor_idフィルタ

- app/Http/Controllers/BlogController.php
- bootstrap/app.php
- config/blog.php
- routes/web.php
- tests/BlogCategoryTest.php
> #53 かてごりーapi

- app/Http/Controllers/BlogController.php
> fix: add Last-Modified

- composer.json
- composer.lock
- database/seeds/AnonymousUserSeeder.php
> #67 [1.6.3] デプロイでseedingにエラーがでる

- app/Http/Controllers/BlogArticleController.php
- app/Http/Controllers/BlogRevisionController.php
- app/Http/Controllers/OGImageController.php
- app/Http/Resources/ArticleResource.php
- app/Http/Resources/RevisionResource.php
- app/Models/Article.php
- app/Models/Revision.php
- composer.json
- composer.lock
- database/factories/ModelFactory.php
- database/migrations/2020_06_21_024650_add_handlename_to_article_and_revision.php
- tests/BlogArticleTest.php
- tests/BlogRevisionTest.php
> #71 はんね枠を追加

- app/Http/Controllers/OGImageController.php
- app/Http/Resources/ArticleResource.php
- app/Http/Resources/RevisionResource.php
~~タイトルの改行コード消し、backでやりたい~~
→やりました
close #70
> #70 ogimage 自由に改行

- composer.json
> Release 1.7.0 to dev

- composer.json
- config/blog.php
> #79 typo: 文科局 -> 分科局

- composer.json
- config/blog.php
> #79 typo: 文科局 -> 分科局 to dev

- app/Http/Controllers/BlogRevisionController.php
> #78 slack通知でauthorが正しく表示されていなかった問題の修正

- routes/web.php
> fix: throttle limit

- phpunit.xml
> #100 phpunit

- app/Http/Controllers/DraftController.php
- app/Http/Controllers/ExhibitionController.php
- app/Http/Middleware/Authenticate.php
- app/Http/Resources/DraftCommentResource.php
- app/Http/Resources/DraftResource.php
- app/Http/Resources/ExhibitionResource.php
- app/Http/Resources/UserResource.php
- app/Libs/Boolean.php
- app/Models/Draft.php
- app/Models/Exhibition.php
- app/Models/User.php
- app/SlackNotify.php
- database/factories/ModelFactory.php
- database/migrations/2020_09_27_104959_create_exhibitions_table.php
- database/migrations/2020_09_27_105115_create_drafts_table.php
- database/migrations/2020_09_29_113041_add_teacher_perm_to_users.php
- database/migrations/2020_09_30_043438_add_user_id_column.php
- database/migrations/2020_10_05_232231_add_category_to_exh.php
- routes/web.php
- tests/AuthJwtTest.php
- tests/DraftTest.php
- tests/ExhibitionTest.php
resolve: #98 
何がお困りかというとテストがうまく使いこなせない、そこをどう解決するか決まったらもうprに成り代わります
> #98 文化祭オンライン展示

- app/Http/Controllers/ExhibitionController.php
- composer.json
> fix: model exist checking

- composer.json
- database/migrations/2020_10_26_072735_change_content_column_in_draft.php
> #111 Contentが長い文字列に対応できるように

- app/Http/Controllers/ExhibitionController.php
- app/Http/Resources/ExhibitionResource.php
- database/migrations/2020_10_29_220915_add_roomid_column.php
> respond room_id

- composer.json
- config/blog.php
> Hotfix #120 make az one category to dev

- app/Http/Controllers/BlogController.php
- composer.json
fix #123
- fix: update Last-Modified
- fix: remove Cache-Control
- v2.2.5
> [hotfix] #123 カテゴリのキャッシュをちゃんとした to dev

- .github/workflows/test_pull.yml
> #131 php のバージョンを指定

- database/factories/ModelFactory.php
- tests/AuthJwtTest.php
- tests/BlogArticleTest.php
- tests/BlogRevisionTest.php
- tests/DraftTest.php
- tests/ImageTest.php
- tests/OGImageTest.php
resolve: #141
正しく直した結果 draft の test に誤りがあったのでついでに修正されています
- test: add multiple user factory types
- test: refactor: use User factory in draft test
- test: to check 403 in draft_public
- test: eliminate authjwt and use actingAs
> #141 すべての Test で actingAs を使うようにした

- database/migrations/2020_02_16_035148_create_revisions_table.php
- database/migrations/2020_02_16_072026_create_articles_table.php
- database/migrations/2020_03_02_182021_create_images_table.php
- database/migrations/2020_03_11_021218_expand_images_blob.php
- database/migrations/2020_06_21_024650_add_handlename_to_article_and_revision.php
- database/migrations/2020_08_24_055926_create_new_users_table.php
- database/migrations/2020_08_24_071317_transfer_users_record.php
- database/migrations/2020_09_27_104959_create_exhibitions_table.php
- database/migrations/2020_09_27_105115_create_drafts_table.php
- database/migrations/2020_09_27_105134_create_draft_comments_table.php
- database/migrations/2020_09_29_113041_add_teacher_perm_to_users.php
- database/migrations/2020_09_30_043438_add_user_id_column.php
- database/migrations/2020_10_05_232231_add_category_to_exh.php
- database/migrations/2020_10_26_072735_change_content_column_in_draft.php
- phpcs.xml
> fix: add migrations for target of phpcs

- composer.json
> #148 ext-jsonをcomposer.jsonに追加した

- .github/workflows/test_pull.yml
- .gitignore
- app/Providers/AppServiceProvider.php
- bootstrap/app.php
- composer.json
- database/factories/ModelFactory.php
- database/migrations/2020_10_26_072735_change_content_column_in_draft.php
- database/migrations/2021_03_12_223739_add_foreign_constraint.php
- phpunit.xml
- tests/BlogArticleTest.php
- tests/BlogRevisionTest.php
- tests/DraftTest.php
- tests/ExhibitionTest.php
- tests/TestCase.php
> テストにmysqlを使用
